#!/bin/bash
mkdir /mongodata -p
mkdir /mongolog -p
touch /mongolog/mongod.log
/opt/mongodb/bin/mongod --rest --replSet rs2 --dbpath /mongodata --port 27017 --logpath /mongolog/mongo.log --logappend > /tmp/mongod.log  2> /tmp/mongod.error &
#web 28017
sleep 3
/opt/mongodb/bin/mongo /root/replicaSet2.js > /tmp/mongo.log 2> /tmp/mongo.error &