#!/bin/bash
/opt/mongodb/bin/mongos --configdb 192.168.1.101,192.168.1.102,192.168.1.103 --port 27017> /tmp/mongos.log  2> /tmp/mongos.error  &
#web 28017
/opt/mongodb/bin/mongo --host 192.168.104 addShard.js > /tmp/addShard.log 2> /tmp/addShard.error
