#!/bin/bash
mkdir /data/configdb -p
mkdir /mongolog -p
touch /mongolog/mongod.log
/opt/mongodb/bin/mongod --rest --configsvr --dbpath /data/configdb --port 27019  --logpath /mongolog/mongo.log --logappend   > /tmp/configsvr.log  2> /tmp/configsvr.error &
#web 28019